### ISSUE TITLE
how to edit model's network but save the same parmas

### ISSUE THREAD

**Issue by Sherlock-hh** [Sherlock-hh/bug_record#8]
yolo模型测试，640分辨率太慢，希望改至320分辨率。遇到的问题记录。

**Comment by Sherlock-hh** [comment]
1、使用rknntool-kit官方中的example/onnx/yolov5/test.py直接运行，连板推理报错，pc端可正常运行出结果

> --> Init runtime environment
> I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
> E RKNNAPI: rknn_init,  msg_load_ack fail, ack = 1(ACK_FAIL), expect 0(ACK_SUCC)!
> E RKNNAPI: ==============================================
> E RKNNAPI: RKNN VERSION:
> E RKNNAPI:   API: 1.7.3 (0cfd4a1 build: 2022-08-15 17:08:57)
> E RKNNAPI:   DRV: 1.7.3 (c4ea832 build: 2022-08-13 09:29:29)
> E RKNNAPI: ==============================================
> E Catch exception when init runtime!
> E Traceback (most recent call last):
> E   File "rknn/api/rknn_base.py", line 936, in rknn.api.rknn_base.RKNNBase.init_runtime
> E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
> E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
> E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
> E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
> E Current device id is: None
> E Devices connected:
> E ['d246427db2d79bee']
> Init runtime environment failed

**Comment by Sherlock-hh** [comment]
test.py的rknn.config和rknn.build中的target platform 都要修改为rv1126

**Comment by Sherlock-hh** [comment]
1、yolov5 在export.py的时候可以直接导出想要的分辨率，前提是必须得是32的倍数
2、训练分辨率最好和检测分辨率保持一致，不然会导致精度下降（与大小无关，尝试过320训练的模型，测试的时候分辨率越大效果越差）
3、模型预处理yolov5用的 letterbox，我最开始测试用的是直接resize，导致精度下降严重。可以视情况修改训练or测试预处理。
4、内存大小够但是硬盘垃圾可以考虑使用ram，具体占用自己算，硬盘优秀的话不用考虑
